#!/bin/sh -e

VERSION=$1
PREV_VERSION=$2
TOP_SRCDIR=${TOP_SRCDIR:-$(cd "$(dirname "$0")/../.." && pwd)}

cd "$TOP_SRCDIR"
. ./packaging/dependencies.env

git checkout refs/tags/release-$VERSION
git log --pretty=fuller --date=short refs/tags/release-$PREV_VERSION..HEAD > ChangeLog

autoreconf -i

./configure && \
    make dist-bzip2 && make dist-gzip && make dist-xz
make distclean

release_mingw()
{
    export HOST=$1
    export LABEL=$2

    mkdir -p mingw-out

    docker build \
	   --build-arg HOST=$HOST \
	   --build-arg ZLIB_VERSION=$ZLIB_VERSION \
	   --build-arg EXPAT_VERSION=$EXPAT_VERSION \
	   --build-arg EXPAT_TAG=$EXPAT_TAG \
	   --build-arg SQLITE_AUTOCONF_VERSION=$SQLITE_AUTOCONF_VERSION \
	   --build-arg SQLITE_YEAR=$SQLITE_YEAR \
	   --build-arg CARES_VERSION=$CARES_VERSION \
	   --build-arg CARES_TAG=$CARES_TAG \
	   --build-arg LIBSSH2_VERSION=$LIBSSH2_VERSION \
	   --build-arg GMP_VERSION=$GMP_VERSION \
	   -f packaging/docker/Dockerfile.mingw \
	   -t aria2-mingw-$HOST .

    docker run --rm -it -v $PWD/mingw-out:/out aria2-mingw-$HOST \
	   cp /aria2/src/aria2c.exe /out

    ./packaging/scripts/mingw-release

    rm -rf mingw-out
}

# mingw 32bit
release_mingw i686-w64-mingw32 win-32bit

# mingw 64bit
release_mingw x86_64-w64-mingw32 win-64bit

# android
mkdir -p android-out

docker build \
       --build-arg ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION \
       --build-arg OPENSSL_VERSION=$OPENSSL_VERSION \
       --build-arg LIBEXPAT_VERSION=$EXPAT_VERSION \
       --build-arg LIBEXPAT_TAG=$EXPAT_TAG \
       --build-arg ZLIB_VERSION=$ZLIB_VERSION \
       --build-arg CARES_VERSION=$CARES_VERSION \
       --build-arg CARES_TAG=$CARES_TAG \
       --build-arg LIBSSH2_VERSION=$LIBSSH2_VERSION \
       -f packaging/docker/Dockerfile.android \
       -t aria2-android .

docker run --rm -it -v $PWD/android-out:/out aria2-android \
       cp /root/build/aria2/src/aria2c /out

./packaging/scripts/android-release

rm -rf android-out

# OSX builds are created separately using makerelease-osx.mk
