set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

option(ARIA2_ENABLE_SSL "Enable SSL/TLS support" ON)
option(ARIA2_ENABLE_BITTORRENT "Enable BitTorrent support" ON)
option(ARIA2_ENABLE_METALINK "Enable Metalink support" ON)
option(ARIA2_ENABLE_WEBSOCKET "Enable WebSocket support" ON)
option(ARIA2_ENABLE_EPOLL "Enable epoll support where available" ON)
option(ARIA2_ENABLE_LIBARIA2 "Build and install libaria2" OFF)
option(ARIA2_ENABLE_WERROR "Treat compiler warnings as errors" OFF)
option(ARIA2_ENABLE_STATIC "Prefer static dependency discovery and static release linking" OFF)
option(ARIA2_WITH_WINTLS "Use Windows native TLS where available" ON)
option(ARIA2_WITH_GNUTLS "Use GnuTLS where available" ON)
option(ARIA2_WITH_OPENSSL "Use OpenSSL where available" ON)
option(ARIA2_WITH_LIBNETTLE "Use nettle where available" ON)
option(ARIA2_WITH_GMP "Use GMP where available" ON)
option(ARIA2_WITH_LIBGCRYPT "Use libgcrypt where available" ON)
option(ARIA2_WITH_LIBXML2 "Use libxml2 where available" ON)
option(ARIA2_WITH_EXPAT "Use Expat where available" ON)
option(ARIA2_WITH_SQLITE3 "Use SQLite3 where available" ON)
option(ARIA2_WITH_CARES "Use c-ares where available" ON)
option(ARIA2_WITH_ZLIB "Use zlib where available" ON)
option(ARIA2_WITH_LIBSSH2 "Use libssh2 where available" ON)
option(ARIA2_WITH_LIBUV "Use libuv where available" OFF)
option(ARIA2_WITH_TCMALLOC "Use tcmalloc where available" OFF)
option(ARIA2_WITH_JEMALLOC "Use jemalloc where available" OFF)
option(ARIA2_WITH_GNUTLS_SYSTEM_CRYPTO_POLICY "Enable GnuTLS system crypto policy" OFF)

set(ARIA2_CA_BUNDLE "" CACHE FILEPATH "CA bundle fallback path for OpenSSL and GnuTLS builds")
set(ARIA2_DEFAULT_DISK_CACHE "" CACHE STRING "Default disk cache size")
set(ARIA2_BASH_COMPLETION_DIR "" CACHE PATH "Bash completion installation directory")

if(ARIA2_ENABLE_STATIC)
  set(PKG_CONFIG_ARGN --static)
endif()

function(aria2_set01 variable value)
  if(${value})
    set(${variable} 1 PARENT_SCOPE)
  else()
    set(${variable} "" PARENT_SCOPE)
  endif()
endfunction()

function(aria2_check_include header variable)
  string(REGEX REPLACE "[^A-Za-z0-9]" "_" _safe "${header}")
  string(TOUPPER "${_safe}" _safe)
  check_include_file("${header}" "${variable}")
endfunction()

function(aria2_check_c_symbol symbol variable)
  set(_headers ${ARGN})
  check_symbol_exists("${symbol}" "${_headers}" "${variable}")
endfunction()

function(aria2_check_c_compiles variable source)
  check_c_source_compiles("${source}" "${variable}")
endfunction()

function(aria2_check_cxx_compiles variable source)
  check_cxx_source_compiles("${source}" "${variable}")
endfunction()

function(aria2_pkg_check module pkg)
  if(PkgConfig_FOUND)
    pkg_check_modules(${module} IMPORTED_TARGET ${pkg})
  endif()
endfunction()

function(aria2_add_pkg_target target module)
  if(TARGET PkgConfig::${module})
    target_link_libraries(${target} PUBLIC PkgConfig::${module})
  endif()
endfunction()

set(ARIA2_MIN_ZLIB_VERSION 1.2.11)
set(ARIA2_MIN_LIBXML2_VERSION 2.9.0)
set(ARIA2_MIN_SQLITE3_VERSION 3.8.0)
set(ARIA2_MIN_LIBCARES_VERSION 1.16.0)
set(ARIA2_MIN_LIBSSH2_VERSION 1.10.0)
set(ARIA2_MIN_LIBUV_VERSION 1.34.0)
set(ARIA2_MIN_GNUTLS_VERSION 3.6.0)
set(ARIA2_MIN_OPENSSL_VERSION 4.0.0)
set(ARIA2_MIN_LIBNETTLE_VERSION 3.5)
set(ARIA2_MIN_LIBGCRYPT_VERSION 1.8.0)
set(ARIA2_MIN_CPPUNIT_VERSION 1.15.0)
