set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

option(ARIA2_ENABLE_SSL "Enable SSL/TLS support" ON)
option(ARIA2_ENABLE_BITTORRENT "Enable BitTorrent support" ON)
option(ARIA2_ENABLE_WEBSOCKET "Enable WebSocket support" ON)
option(ARIA2_ENABLE_EPOLL "Enable epoll support where available" ON)
option(ARIA2_ENABLE_WERROR "Treat compiler warnings as errors" OFF)
option(ARIA2_ENABLE_STATIC "Prefer static dependency discovery and static release linking" OFF)
option(ARIA2_RELEASE_SIZE_OPTIMIZED "Optimize release binaries for size and linker garbage collection" OFF)
option(ARIA2_RELEASE_LTO "Enable interprocedural optimization for release builds when supported" OFF)
option(ARIA2_WITH_ZLIB "Use zlib where available" ON)
option(ARIA2_WITH_TCMALLOC "Use tcmalloc where available" OFF)
option(ARIA2_WITH_JEMALLOC "Use jemalloc where available" OFF)

set(ARIA2_CA_BUNDLE "" CACHE FILEPATH "CA bundle fallback path for OpenSSL builds")
set(ARIA2_DEFAULT_DISK_CACHE "" CACHE STRING "Default disk cache size")
set(ARIA2_BASH_COMPLETION_DIR "" CACHE PATH "Bash completion installation directory")

if(ARIA2_ENABLE_STATIC)
  set(PKG_CONFIG_ARGN --static)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
  endif()
endif()

function(aria2_set01 variable value)
  if(${value})
    set(${variable} 1 PARENT_SCOPE)
  else()
    set(${variable} "" PARENT_SCOPE)
  endif()
endfunction()

function(aria2_check_include header variable)
  string(REGEX REPLACE "[^A-Za-z0-9]" "_" _safe "${header}")
  string(TOUPPER "${_safe}" _safe)
  check_include_file("${header}" "${variable}")
endfunction()

function(aria2_check_c_symbol symbol variable)
  set(_headers ${ARGN})
  check_symbol_exists("${symbol}" "${_headers}" "${variable}")
endfunction()

function(aria2_check_c_compiles variable source)
  check_c_source_compiles("${source}" "${variable}")
endfunction()

function(aria2_check_cxx_compiles variable source)
  check_cxx_source_compiles("${source}" "${variable}")
endfunction()

function(aria2_pkg_check module pkg)
  if(PkgConfig_FOUND)
    pkg_check_modules(${module} IMPORTED_TARGET ${pkg})
  endif()
endfunction()

function(aria2_add_pkg_target target module)
  if(TARGET PkgConfig::${module})
    target_link_libraries(${target} PUBLIC PkgConfig::${module})
  endif()
endfunction()

set(ARIA2_MIN_ZLIB_VERSION 1.2.11)
set(ARIA2_MIN_LIBCURL_VERSION 8.0.0)
set(ARIA2_MIN_OPENSSL_VERSION 3.5.0)
set(ARIA2_MIN_BOOST_VERSION 1.75.0)
set(ARIA2_MIN_CPPUNIT_VERSION 1.15.0)
