message(STATUS "Build: ${BUILD}")
message(STATUS "Host: ${HOST}")
message(STATUS "Target: ${TARGET}")
message(STATUS "Features: SSL=${ENABLE_SSL}; WinTLS=${HAVE_WINTLS}; GnuTLS=${HAVE_LIBGNUTLS}; OpenSSL=${HAVE_OPENSSL}; BitTorrent=${ENABLE_BITTORRENT}; ED2K=${ENABLE_ED2K}; Metalink=${ENABLE_METALINK}; XML-RPC=${ENABLE_XML_RPC}; WebSocket=${ENABLE_WEBSOCKET}; Async DNS=${ENABLE_ASYNC_DNS}; libaria2=${ENABLE_LIBARIA2}")
