set(ARIA2_CORE_SOURCES ${ARIA2_SOURCES_BASE})
if(WIN32)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_MINGW_BUILD})
endif()
if(ENABLE_WEBSOCKET)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_WEBSOCKET})
else()
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_ENABLE_WEBSOCKET})
endif()
if(HAVE_SOME_XMLLIB)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_SOME_XMLLIB})
endif()
if(HAVE_LIBXML2)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBXML2})
endif()
if(HAVE_LIBEXPAT)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBEXPAT})
endif()
if(ENABLE_XML_RPC)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_XML_RPC})
endif()
if(HAVE_SOME_FALLOCATE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_SOME_FALLOCATE})
endif()
if(HAVE_EPOLL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_EPOLL})
endif()
if(ENABLE_SSL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_SSL})
endif()
if(HAVE_WINTLS)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_WINTLS})
endif()
if(USE_INTERNAL_MD)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_USE_INTERNAL_MD})
endif()
if(HAVE_LIBGNUTLS)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBGNUTLS})
endif()
if(HAVE_LIBGCRYPT)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBGCRYPT})
endif()
if(HAVE_LIBGCRYPT AND USE_LIBGCRYPT_MD)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBGCRYPT__USE_LIBGCRYPT_MD})
endif()
if(HAVE_LIBNETTLE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBNETTLE})
endif()
if(HAVE_LIBNETTLE AND USE_LIBNETTLE_MD)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBNETTLE__USE_LIBNETTLE_MD})
endif()
if(HAVE_LIBGMP)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBGMP})
endif()
if(HAVE_OPENSSL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_OPENSSL})
endif()
if(HAVE_OPENSSL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_OPENSSL_TLS})
endif()
if(HAVE_OPENSSL AND USE_OPENSSL_MD)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_OPENSSL__USE_OPENSSL_MD})
endif()
if(HAVE_ZLIB)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_ZLIB})
endif()
if(HAVE_SQLITE3)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_SQLITE3})
endif()
if(HAVE_LIBSSH2)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBSSH2})
endif()
if(ENABLE_ASYNC_DNS)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_ASYNC_DNS})
endif()
if(ENABLE_BITTORRENT)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_BITTORRENT})
  if(USE_INTERNAL_BIGNUM)
    list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_BITTORRENT__USE_INTERNAL_BIGNUM})
  endif()
  if(USE_INTERNAL_ARC4)
    list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_BITTORRENT__USE_INTERNAL_ARC4})
  endif()
endif()
if(ENABLE_METALINK)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_METALINK})
endif()
if(NOT HAVE_ASCTIME_R)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_ASCTIME_R})
endif()
if(NOT HAVE_BASENAME)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_BASENAME})
endif()
if(NOT HAVE_GETADDRINFO)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_GETADDRINFO})
endif()
if(NOT HAVE_GAI_STRERROR)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_GAI_STRERROR})
endif()
if(NOT HAVE_GETTIMEOFDAY)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_GETTIMEOFDAY})
endif()
if(NOT HAVE_LOCALTIME_R)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_LOCALTIME_R})
endif()
if(NOT HAVE_STRPTIME)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_STRPTIME})
endif()
if(NOT HAVE_TIMEGM)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_TIMEGM})
endif()
if(NOT HAVE_DAEMON)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_DAEMON})
endif()
if(HAVE_POLL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_POLL})
endif()
if(HAVE_PORT_ASSOCIATE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_PORT_ASSOCIATE})
endif()
if(HAVE_KQUEUE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_KQUEUE})
endif()
if(HAVE_LIBUV)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_LIBUV})
endif()
if(ENABLE_LIBARIA2)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_LIBARIA2})
endif()

list(REMOVE_DUPLICATES ARIA2_CORE_SOURCES)

add_library(wslay STATIC
  third_party/wslay/lib/wslay_event.c
  third_party/wslay/lib/wslay_frame.c
  third_party/wslay/lib/wslay_net.c
  third_party/wslay/lib/wslay_queue.c)
target_include_directories(wslay
  PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/third_party/wslay/lib/includes
    ${CMAKE_CURRENT_BINARY_DIR}/third_party/wslay/lib/includes
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/third_party/wslay/lib
    ${CMAKE_CURRENT_BINARY_DIR})
target_compile_definitions(wslay PRIVATE HAVE_CONFIG_H WSLAY_VERSION="${PROJECT_VERSION}")

if(ENABLE_LIBARIA2)
  add_library(aria2_core ${ARIA2_CORE_SOURCES})
  set_target_properties(aria2_core PROPERTIES OUTPUT_NAME aria2)
else()
  add_library(aria2_core STATIC ${ARIA2_CORE_SOURCES})
endif()

target_compile_definitions(aria2_core PUBLIC HAVE_CONFIG_H)
target_include_directories(aria2_core
  PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/src
    ${CMAKE_CURRENT_SOURCE_DIR}/src/includes
    ${CMAKE_CURRENT_BINARY_DIR}
    ${CMAKE_CURRENT_BINARY_DIR}/src/includes
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/lib)
if(ENABLE_WEBSOCKET)
  target_link_libraries(aria2_core PUBLIC wslay)
endif()
if(HAVE_ZLIB)
  aria2_add_pkg_target(aria2_core ZLIB)
endif()
if(HAVE_LIBXML2)
  aria2_add_pkg_target(aria2_core LIBXML2)
endif()
if(HAVE_LIBEXPAT)
  aria2_add_pkg_target(aria2_core EXPAT)
endif()
if(HAVE_SQLITE3)
  aria2_add_pkg_target(aria2_core SQLITE3)
endif()
if(HAVE_LIBCARES)
  aria2_add_pkg_target(aria2_core LIBCARES)
endif()
if(HAVE_LIBSSH2)
  aria2_add_pkg_target(aria2_core LIBSSH2)
endif()
if(HAVE_LIBUV)
  aria2_add_pkg_target(aria2_core LIBUV)
endif()
if(HAVE_LIBGNUTLS)
  aria2_add_pkg_target(aria2_core LIBGNUTLS)
endif()
if(HAVE_OPENSSL)
  aria2_add_pkg_target(aria2_core OPENSSL)
endif()
if(HAVE_LIBNETTLE)
  aria2_add_pkg_target(aria2_core LIBNETTLE)
endif()
if(HAVE_LIBGCRYPT)
  aria2_add_pkg_target(aria2_core LIBGCRYPT)
endif()
if(HAVE_LIBGMP)
  target_link_libraries(aria2_core PUBLIC gmp)
endif()
if(WIN32)
  target_link_libraries(aria2_core PUBLIC ws2_32 wsock32 gdi32 winmm iphlpapi psapi crypt32 secur32 advapi32)
endif()
if(CMAKE_SYSTEM_NAME MATCHES "SunOS")
  target_link_libraries(aria2_core PUBLIC nsl socket)
endif()
if(ARIA2_WITH_TCMALLOC)
  aria2_pkg_check(TCMALLOC "libtcmalloc_minimal")
  if(TCMALLOC_FOUND)
    target_link_libraries(aria2_core PUBLIC PkgConfig::TCMALLOC)
  else()
    target_link_libraries(aria2_core PUBLIC tcmalloc_minimal)
  endif()
endif()
if(ARIA2_WITH_JEMALLOC)
  aria2_pkg_check(JEMALLOC "jemalloc")
  if(JEMALLOC_FOUND)
    target_link_libraries(aria2_core PUBLIC PkgConfig::JEMALLOC)
  else()
    target_link_libraries(aria2_core PUBLIC jemalloc)
  endif()
endif()

if(ARIA2_ENABLE_WERROR)
  target_compile_options(aria2_core PRIVATE -Werror)
endif()

add_executable(aria2-next src/main.cc)
target_link_libraries(aria2-next PRIVATE aria2_core)

if(ARIA2_RELEASE_SIZE_OPTIMIZED)
  foreach(target wslay aria2_core aria2-next)
    target_compile_options(${target} PRIVATE
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang,AppleClang>:-Os>
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang,AppleClang>:-ffunction-sections>
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang,AppleClang>:-fdata-sections>
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang,AppleClang>:-Os>
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang,AppleClang>:-ffunction-sections>
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang,AppleClang>:-fdata-sections>)
  endforeach()

  if(APPLE)
    target_link_options(aria2-next PRIVATE -Wl,-dead_strip)
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    target_link_options(aria2-next PRIVATE -Wl,--gc-sections)
  endif()
endif()

if(ARIA2_RELEASE_LTO)
  check_ipo_supported(RESULT aria2_ipo_supported OUTPUT aria2_ipo_output LANGUAGES C CXX)
  if(aria2_ipo_supported)
    set_property(TARGET wslay aria2_core aria2-next PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  else()
    message(WARNING "ARIA2_RELEASE_LTO requested but IPO is not supported: ${aria2_ipo_output}")
  endif()
endif()

if(ARIA2_ENABLE_STATIC)
  if(WIN32)
    target_link_options(aria2-next PRIVATE -static -static-libgcc -static-libstdc++)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_package(Threads REQUIRED)
    target_link_options(aria2-next PRIVATE -static -static-libgcc -static-libstdc++)
    target_link_libraries(aria2-next PRIVATE Threads::Threads ${CMAKE_DL_LIBS} rt)
  endif()
endif()

install(TARGETS aria2-next RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
if(ENABLE_LIBARIA2)
  install(TARGETS aria2_core
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
  install(DIRECTORY src/includes/aria2 DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/src/libaria2.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
endif()
