set(ARIA2_CORE_SOURCES ${ARIA2_SOURCES_BASE})
if(WIN32)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_MINGW_BUILD})
endif()
if(ENABLE_WEBSOCKET)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_WEBSOCKET})
else()
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_ENABLE_WEBSOCKET})
endif()
if(HAVE_SOME_FALLOCATE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_SOME_FALLOCATE})
endif()
if(HAVE_EPOLL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_EPOLL})
endif()
if(ENABLE_SSL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_SSL})
endif()
if(HAVE_OPENSSL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_OPENSSL})
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_OPENSSL_TLS})
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_OPENSSL_DIGEST})
endif()
if(HAVE_ZLIB)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_ZLIB})
endif()
if(ENABLE_BITTORRENT)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_ENABLE_BITTORRENT})
endif()
if(NOT HAVE_ASCTIME_R)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_ASCTIME_R})
endif()
if(NOT HAVE_BASENAME)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_BASENAME})
endif()
if(NOT HAVE_GETADDRINFO)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_GETADDRINFO})
endif()
if(NOT HAVE_GAI_STRERROR)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_GAI_STRERROR})
endif()
if(NOT HAVE_GETTIMEOFDAY)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_GETTIMEOFDAY})
endif()
if(NOT HAVE_LOCALTIME_R)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_LOCALTIME_R})
endif()
if(NOT HAVE_STRPTIME)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_STRPTIME})
endif()
if(NOT HAVE_TIMEGM)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_TIMEGM})
endif()
if(NOT HAVE_DAEMON)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_NOT_HAVE_DAEMON})
endif()
if(HAVE_POLL)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_POLL})
endif()
if(HAVE_PORT_ASSOCIATE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_PORT_ASSOCIATE})
endif()
if(HAVE_KQUEUE)
  list(APPEND ARIA2_CORE_SOURCES ${ARIA2_SOURCES_HAVE_KQUEUE})
endif()

list(REMOVE_DUPLICATES ARIA2_CORE_SOURCES)

add_library(aria2_core STATIC ${ARIA2_CORE_SOURCES})

target_compile_definitions(aria2_core PUBLIC HAVE_CONFIG_H)
target_include_directories(aria2_core
  PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/src
    ${CMAKE_CURRENT_BINARY_DIR}
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/lib)
if(HAVE_ZLIB)
  aria2_add_pkg_target(aria2_core ZLIB)
endif()
aria2_add_pkg_target(aria2_core LIBCURL)
if(HAVE_OPENSSL)
  aria2_add_pkg_target(aria2_core OPENSSL)
endif()
target_link_libraries(aria2_core PUBLIC Boost::json spdlog::spdlog)
if(HAVE_LIBTORRENT_RASTERBAR)
  aria2_add_pkg_target(aria2_core LIBTORRENT_RASTERBAR)
  target_link_libraries(aria2_core PUBLIC Boost::headers)
endif()
if(WIN32)
  target_compile_definitions(aria2_core PUBLIC
    ARIA2_WINDOWS_TARGET_VERSION=${ARIA2_WINDOWS_TARGET_VERSION}
    WINVER=${ARIA2_WINDOWS_TARGET_VERSION}
    _WIN32_WINNT=${ARIA2_WINDOWS_TARGET_VERSION})
  target_link_libraries(aria2_core PUBLIC ws2_32 wsock32 gdi32 winmm iphlpapi psapi crypt32 secur32 advapi32)
endif()
if(CMAKE_SYSTEM_NAME MATCHES "SunOS")
  target_link_libraries(aria2_core PUBLIC nsl socket)
endif()
if(ARIA2_WITH_TCMALLOC)
  aria2_pkg_check(TCMALLOC "libtcmalloc_minimal")
  if(TCMALLOC_FOUND)
    target_link_libraries(aria2_core PUBLIC PkgConfig::TCMALLOC)
  else()
    target_link_libraries(aria2_core PUBLIC tcmalloc_minimal)
  endif()
endif()
if(ARIA2_WITH_JEMALLOC)
  aria2_pkg_check(JEMALLOC "jemalloc")
  if(JEMALLOC_FOUND)
    target_link_libraries(aria2_core PUBLIC PkgConfig::JEMALLOC)
  else()
    target_link_libraries(aria2_core PUBLIC jemalloc)
  endif()
endif()

if(ARIA2_ENABLE_WERROR)
  target_compile_options(aria2_core PRIVATE -Werror)
endif()

add_executable(aria2-next src/main.cc)
target_link_libraries(aria2-next PRIVATE aria2_core)

if(ARIA2_RELEASE_SIZE_OPTIMIZED)
  foreach(target aria2_core aria2-next)
    target_compile_options(${target} PRIVATE
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang,AppleClang>:-Os>
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang,AppleClang>:-ffunction-sections>
      $<$<COMPILE_LANG_AND_ID:C,GNU,Clang,AppleClang>:-fdata-sections>
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang,AppleClang>:-Os>
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang,AppleClang>:-ffunction-sections>
      $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang,AppleClang>:-fdata-sections>)
  endforeach()

  if(APPLE)
    target_link_options(aria2-next PRIVATE -Wl,-dead_strip)
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    target_link_options(aria2-next PRIVATE -Wl,--gc-sections)
  endif()
endif()

if(ARIA2_RELEASE_LTO)
  check_ipo_supported(RESULT aria2_ipo_supported OUTPUT aria2_ipo_output LANGUAGES C CXX)
  if(aria2_ipo_supported)
    set_property(TARGET aria2_core aria2-next PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  else()
    message(WARNING "ARIA2_RELEASE_LTO requested but IPO is not supported: ${aria2_ipo_output}")
  endif()
endif()

if(ARIA2_ENABLE_STATIC)
  if(WIN32)
    target_link_options(aria2-next PRIVATE -static -static-libgcc -static-libstdc++)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_package(Threads REQUIRED)
    target_link_options(aria2-next PRIVATE -static -static-libgcc -static-libstdc++)
    target_link_libraries(aria2-next PRIVATE Threads::Threads ${CMAKE_DL_LIBS} rt)
  endif()
endif()

install(TARGETS aria2-next RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
