# Source inventory for conditional aria2 CTest targets.

set(ARIA2_TEST_SOURCES_BASE
  tests/AllTest.cc
  tests/TestUtil.cc
  tests/TestUtil.h
  tests/SocketCoreTest.cc
  tests/array_funTest.cc
  tests/Base64Test.cc
  tests/Base32Test.cc
  tests/a2functionalTest.cc
  tests/FileEntryTest.cc
  tests/PieceTest.cc
  tests/SegmentTest.cc
  tests/GrowSegmentTest.cc
  tests/SingleFileAllocationIteratorTest.cc
  tests/StorageTruthTest.cc
  tests/DefaultProgressInfoFileTest.cc
  tests/RequestGroupTest.cc
  tests/UtilTest1.cc
  tests/UtilTest2.cc
  tests/UtilSecurityTest.cc
  tests/UriListParserTest.cc
  tests/HttpHeaderProcessorTest.cc
  tests/HttpRangeValidatorTest.cc
  tests/CurlRequestContextTest.cc
  tests/HttpErrorPageDetectorTest.cc
  tests/RequestTest.cc
  tests/RequestGroupManTest.cc
  tests/OptionHandlerTest.cc
  tests/SegmentManTest.cc
  tests/BitfieldManTest.cc
  tests/SingletonHolderTest.cc
  tests/HttpHeaderTest.cc
  tests/FileTest.cc
  tests/OptionTest.cc
  tests/DefaultDiskWriterTest.cc
  tests/FeatureConfigTest.cc
  tests/VersionUsageTest.cc
  tests/SpeedCalcTest.cc
  tests/MultiDiskAdaptorTest.cc
  tests/MultiFileAllocationIteratorTest.cc
  tests/FixedNumberRandomizer.h
  tests/ProtocolDetectorTest.cc
  tests/ExceptionTest.cc
  tests/FmtTest.cc
  tests/DownloadEngineTest.cc
  tests/SignatureTest.cc
  tests/ServerStatManTest.cc
  tests/FeedbackURISelectorTest.cc
  tests/InorderURISelectorTest.cc
  tests/ServerStatTest.cc
  tests/DirectDiskAdaptorTest.cc
  tests/TimeTest.cc
  tests/OptionParserTest.cc
  tests/DNSCacheTest.cc
  tests/DownloadHelperTest.cc
  tests/SequentialPickerTest.cc
  tests/RarestPieceSelectorTest.cc
  tests/PieceStatManTest.cc
  tests/InorderPieceSelector.h
  tests/LongestSequencePieceSelectorTest.cc
  tests/a2algoTest.cc
  tests/bitfieldTest.cc
  tests/DownloadContextTest.cc
  tests/SessionSerializerTest.cc
  tests/ValueBaseTest.cc
  tests/ChunkedDecodingStreamFilterTest.cc
  tests/UriTest.cc
  tests/UriSplitTest.cc
  tests/MockSegment.h
  tests/JsonTest.cc
  tests/LogTest.cc
  tests/RpcResponseTest.cc
  tests/RpcMethodTest.cc
  tests/RpcHttpHandlerTest.cc
  tests/WebSocketSessionManTest.cc
  tests/BufferedFileTest.cc
  tests/GeomStreamPieceSelectorTest.cc
  tests/SegListTest.cc
  tests/ParamedStringTest.cc
  tests/RpcHelperTest.cc
  tests/AbstractCommandTest.cc
  tests/SinkStreamFilterTest.cc
  tests/WrDiskCacheTest.cc
  tests/WrDiskCacheEntryTest.cc
  tests/GroupIdTest.cc
  tests/IndexedListTest.cc
  tests/SimpleRandomizerTest.cc
  tests/MessageDigestHelperTest.cc
  tests/IteratableChunkChecksumValidatorTest.cc
  tests/IteratableChecksumValidatorTest.cc
  tests/MessageDigestTest.cc
  tests/Ed2kHelperTest.cc
  tests/Ed2kPolicyWindowsMacroSmokeTest.cc
  tests/Ed2kCommandTest.cc
  tests/Ed2kKadStateTest.cc
  tests/Ed2kSharedStoreTest.cc
)

set(ARIA2_TEST_SOURCES_HAVE_SOME_FALLOCATE
  tests/FallocFileAllocationIteratorTest.cc
)

set(ARIA2_TEST_SOURCES_HAVE_ZLIB
  tests/GZipDecoder.cc
  tests/GZipDecoder.h
  tests/GZipDecoderTest.cc
  tests/GZipEncoderTest.cc
  tests/GZipDecodingStreamFilterTest.cc
  tests/GZipFileTest.cc
)

set(ARIA2_TEST_SOURCES_ENABLE_BITTORRENT
  tests/BittorrentHelperTest.cc
  tests/MagnetTest.cc
  tests/Bencode2Test.cc
  tests/LibtorrentSeedPolicyTest.cc
)

set(ARIA2_TEST_SOURCES_NOT_HAVE_TIMEGM
  tests/TimegmTest.cc
)
